version: '3.8'

services:
  go-app:
    build: ./go-app
    ports:
      - "8000:8000"

  nextjs-app:
    build: ./nextjs-app
    ports:
      - "3000:3000"

  wordpress-app:
    build: ./wordpress-app
    ports:
      - "8080:80"
    volumes:
      - ./wordpress-app/wp-content:/var/www/html/wp-content