name: CI

on:
  push:
    branches: [main, 'feature/*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.4
    - name: Install dependencies
      run: go mod tidy
    - name: Run Linter
      run: golangci-lint run ./...
    - name: Run Tests
      run: go test ./...